ProjetWeb-main/src/Entity/Note.php
<?php

namespace App\Entity;

use App\Repository\NoteRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=NoteRepository::class)
 */
class Note
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="integer")
     */
    private $anneScolaire;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $noteDS;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $noteTp;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $noteExamen;

    /**
     * @ORM\Column(type="boolean")
     */
    private $dsValid;

    /**
     * @ORM\Column(type="boolean")
     */
    private $tpValid;

    /**
     * @ORM\Column(type="boolean")
     */
    private $ExamenValid;

    /**
     * @ORM\ManyToOne(targetEntity=MatiereNiveauFiliere::class, inversedBy="notes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $matiere;

    /**
     * @ORM\ManyToOne(targetEntity=Etudiant::class, inversedBy="notes")
     * @ORM\JoinColumn(nullable=false)
     */
    private $etudiant;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getAnneScolaire(): ?int
    {
        return $this->anneScolaire;
    }

    public function setAnneScolaire(int $anneScolaire): self
    {
        $this->anneScolaire = $anneScolaire;

        return $this;
    }

    public function getNoteDS(): ?float
    {
        return $this->noteDS;
    }

    public function setNoteDS(float $noteDS): self
    {
        $this->noteDS = $noteDS;

        return $this;
    }

    public function getNoteTp(): ?float
    {
        return $this->noteTp;
    }

    public function setNoteTp(float $noteTp): self
    {
        $this->noteTp = $noteTp;

        return $this;
    }

    public function getNoteExamen(): ?float
    {
        return $this->noteExamen;
    }

    public function setNoteExamen(float $noteExamen): self
    {
        $this->noteExamen = $noteExamen;

        return $this;
    }

    public function getDsValid(): ?bool
    {
        return $this->dsValid;
    }

    public function setDsValid(bool $dsValid): self
    {
        $this->dsValid = $dsValid;

        return $this;
    }

    public function getTpValid(): ?bool
    {
        return $this->tpValid;
    }

    public function setTpValid(bool $tpValid): self
    {
        $this->tpValid = $tpValid;

        return $this;
    }

    public function getExamenValid(): ?bool
    {
        return $this->ExamenValid;
    }

    public function setExamenValid(bool $ExamenValid): self
    {
        $this->ExamenValid = $ExamenValid;

        return $this;
    }

    public function getMatiere(): ?MatiereNiveauFiliere
    {
        return $this->matiere;
    }

    public function setMatiere(?MatiereNiveauFiliere $matiere): self
    {
        $this->matiere = $matiere;

        return $this;
    }

    public function getEtudiant(): ?Etudiant
    {
        return $this->etudiant;
    }

    public function setEtudiant(?Etudiant $etudiant): self
    {
        $this->etudiant = $etudiant;

        return $this;
    }
}

ProjetWeb-main/src/Controller/ValidateurController.php
<?php

namespace App\Controller;

use App\Entity\Note;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ValidateurController extends AbstractController
{
    #[Route('/validateur', name: 'validateur')]
    public function index(): Response
    {
        $repository = $this->getDoctrine()->getRepository('App:Filiere');
        $filiere = $repository->findall();


        $filieres=array();
        foreach($filiere as $fil){
            $niveau=$fil->getNiveaux();
            $fila=$fil->getFiliere();
            $filieres[$fila]=array();
            foreach($niveau as $niv){
                array_push($filieres[$fila],$niv->getNiveau());


            }
        }



        return $this->render('validateur/index.html.twig', [
            'filieres'=>$filieres,
            'title' => 'Validateur',

        ]);
    }


    #[Route('/validateur/{semester}/{filiere}/{niveau}', name: 'matiereValide')]
    public function mats(Request $request,int $semester,string $filiere,int $niveau): Response
    {
        $repository = $this->getDoctrine()->getRepository('App:Filiere');
        $repository2 = $this->getDoctrine()->getRepository('App:MatiereNiveauFiliere');
        $repository3= $this->getDoctrine()->getRepository('App:Niveau');
        $repository4= $this->getDoctrine()->getRepository('App:Note');
        $repository5= $this->getDoctrine()->getRepository('App:Etudiant');

        $fil = $repository->findOneBy(['filiere'=>$filiere]);
        $niv = $repository3->findOneBy(['niveau'=>$niveau]);
        $matieres=$repository2->findall();


            if($fil){
                $filId=$fil->getId();
            }else{
                return $this->redirectToRoute('not_found');
            }



            if($niv){
                $nivId=$niv->getId();

            }else{
                return $this->redirectToRoute('not_found');
            }



        foreach($matieres as $mat){
            $matName=$mat->getMatiere()->getNom();


            $ds=true;
            $tp=true;
            $exam=true;

            $etudiants=$repository5->findBy(['filiere'=>$fil , 'niveau'=>$niv]);

            $notes=$repository4->findBy(['matiere'=>$mat]);

            if($notes==null){
                $ds=false;
                $tp=false;
                $exam=false;}
            else {
                foreach ($etudiants as $etudiant) {

                    foreach ($notes as $note) {
                        if ($note->getEtudiant() == $etudiant) {
                            if ($note->getNoteDS() == null) {
                                $ds = false;
                            }
                            if ($note->getNoteTp() == null) {
                                $tp = false;
                            }
                            if ($note->getNoteExamen() == null) {
                                $exam = false;
                            }

                        }
                    }
                }
            }


            if($mat->getFiliere()->getId()==$filId && $mat->getNiveau()->getId()==$nivId && ($ds==true || $tp==true ||$exam==true)){
                $matiere[$matName]=array();
                if($mat->getTp() && $tp==true){ array_push($matiere[$matName],"TP");}
                if($mat->getDs() && $ds==true){ array_push($matiere[$matName],"DS");}
                if($mat->getExamen() && $exam==true){ array_push($matiere[$matName],"Exam");}

            }
            else{$matiere=array();}
        }



        return $this->render('validateur/matieresV.html.twig', [
            'controller_name' => 'ScolariteController',
            'matiere'=>$matiere,
            'title' => 'Matieres',
            'semester'=>$semester,
            'filiere'=>$filiere,
            'niveau'=>$niveau
        ]);
    }


    #[Route('/validateur/{semester}/{filiere}/{niveau}/{matiere}/{type}', name: 'validation')]
    public function notes(Request $request,int $semester,string $filiere,int $niveau, string $type,string $matiere): Response
    {
        $repository = $this->getDoctrine()->getRepository('App:Etudiant');
        $repository2 = $this->getDoctrine()->getRepository('App:Matiere');
        $repository3 = $this->getDoctrine()->getRepository('App:MatiereNiveauFiliere');
        $repository4 = $this->getDoctrine()->getRepository('App:Filiere');
        $repository5 = $this->getDoctrine()->getRepository('App:Niveau');
        $repository6 = $this->getDoctrine()->getRepository('App:Note');

        $fil=$repository4->findOneBy(['filiere'=>$filiere]);
        $niv=$repository5->findOneBy(['niveau'=>$niveau]);

        $etudiants=$repository->findAll();
        $mat=$repository2->findOneBy(['nom'=>$matiere]);

        if(!$mat){return $this->redirectToRoute('not_found');}
        if(!$fil){return $this->redirectToRoute('not_found');}
        if(!$niv){return $this->redirectToRoute('not_found');}

        if($semester!=1 && $semester!=2){return $this->redirectToRoute('not_found');}
        if(strtoupper($type)<>"DS" && strtoupper($type)<>"TP" && strtoupper($type)!="EXAM"){return $this->redirectToRoute('not_found');}

        $matNivFil=$repository3->findOneBy(['matiere'=>$mat]);

        $notes=array();

        foreach($etudiants as $etudiant){
            if($etudiant->getFiliere()->getFiliere()==$filiere && $etudiant->getNiveau()->getNiveau()==$niveau ){

                $note=$repository6->findOneBy(['etudiant'=>$etudiant,'matiere'=>$matNivFil ]);

                array_push($notes,$note);

            }
        }




        if($request->isMethod('post')){
            $posts = $request->request->all();

            unset($posts["DataTables_Table_0_length"]);

            foreach($etudiants as $etudiant){
                foreach ($posts as $key=>$post){
                    $etudiant=$repository->findOneBy(['numInscription'=>$key]);
                    if($etudiant){
                        $note=$repository6->findOneBy(['etudiant'=>$etudiant,'matiere'=>$matNivFil ]);
                        if(strtoupper($type)=="DS" && strtoupper($type)<>"TP" && strtoupper($type)!="EXAM"){
                            $note->setDsValid("true");
                            $entityManager = $this->getDoctrine()->getManager();
                            $entityManager->flush();
                        }
                        if( strtoupper($type)=="TP"){
                            $note->setTpValid("true");
                            $entityManager = $this->getDoctrine()->getManager();
                            $entityManager->flush();
                        }
                        if(  strtoupper($type)=="EXAM"){
                            $note->setExamenValid("true");
                            $entityManager = $this->getDoctrine()->getManager();
                            $entityManager->flush();
                        }
                    }
                }
            }



        }




        return $this->render('validateur/validation.html.twig', [
            'etudiants'=>$notes,
            'title' => 'validation',
            'type'=>$type
        ]);

    }





}

ProjetWeb-main/templates/validateur/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}

    <div class="accordion" id="accordionExample">
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button " type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="false" aria-controls="collapseOne">
                    Semester 1
                </button>
            </h2>
            <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
                <div class="accordion-body">



                    <div class="accordion" id="accordionExample2">
                        {% for fil,niveau in filieres %}
                            <div class="accordion-item">
                                <h2 class="accordion-header" id="headingOne">
                                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapse{{ fil }}" aria-expanded="true" aria-controls="collapse{{ fil }}">
                                        {{ fil }}
                                    </button>
                                </h2>
                                <div id="collapse{{ fil }}" class="accordion-collapse collapse " aria-labelledby="headingOne" data-bs-parent="#accordionExample2">
                                    <div class="accordion-body">

                                        {% for key,niv in niveau %}

                                            <div class="list-group">
                                                <a href="{{ path('matiereValide',{'semester':"1", 'filiere':fil , 'niveau':niv }) }}"  class="list-group-item list-group-item-action">{{ fil }} {{ niv }}</a></li>
                                            </div>

                                        {% endfor %}


                                    </div>
                                </div>
                            </div>
                        {% endfor %}


                    </div>
                </div>
            </div>
        </div>

        <div class="accordion-item">
            <h2 class="accordion-header" id="headingTwo">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
                    Semester 2
                </button>
            </h2>
            <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
                <div class="accordion-body">
                    <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
                </div>
            </div>
        </div>

    </div>




{% endblock %}

ProjetWeb-main/templates/validateur/matieresV.html.twig
{% extends 'base.html.twig' %}


{% block body %}


    {% for mat,ex in matiere %}
        <div class="accordion-item">
            <h2 class="accordion-header" id="headingOne">
                <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                        data-bs-target="#collapse{{ mat }}" aria-expanded="true" aria-controls="collapse{{ mat }}">
                    {{ mat }}
                </button>
            </h2>
            <div id="collapse{{ mat }}" class="accordion-collapse collapse " aria-labelledby="headingOne"
                 data-bs-parent="#accordionExample2">
                <div class="accordion-body">


                    {% for key,typeEx in ex %}

                        <div class="list-group">
                            <a href="{{ path('notes',{'semester':semester, 'filiere':filiere , 'niveau':niveau , 'matiere':mat , 'type':typeEx }) }}" class="list-group-item list-group-item-action" > {{ typeEx }}</a>

                        </div>
                    {% endfor %}







                </div>
            </div>
        </div>
    {% endfor %}









{% endblock %}

ProjetWeb-main/templates/validateur/validation.html.twig
{% extends 'table.html.twig' %}

{% block body %}

    <form method="POST" id="my_form2">
        <table  class="table" >
            <thead>
            <tr>
                <th>num_inscription</th>
                <th>nom</th>
                <th>prenom</th>
                <th>note</th>
                <th>validation</th>
            </tr>
            </thead>
            {% for etud in etudiants %}
                <tr>
                    <td>{{ etud.etudiant.numInscription }}</td>

                    <td>{{ etud.etudiant.nom }}</td>
                    <td>{{ etud.etudiant.prenom }}</td>
                    {% if type|upper == "DS" %}
                        <td>{{ etud.noteDS }}</td>
                    {% endif %}
                    {% if type|upper == "TP" %}
                        <td>{{ etud.noteTp }}</td>
                    {% endif %}
                    {% if type|upper == "EXAMEN" %}
                        <td>{{ etud.noteExamen }}</td>
                    {% endif %}
                    <td>
                        {% if  (type|upper == "DS" and etud.dsValid) or (type|upper == "TP" and etud.tpValid) or (type|upper == "EXAM" and etud.examenValid)   %}
                        <input class="form-check-input" type="checkbox" id="my_form2" name={{etud.etudiant.numInscription}} checked>
                        {% else %}
                            <input class="form-check-input" type="checkbox" id="my_form2" name={{etud.etudiant.numInscription}} >
                        {% endif %}


                    </td>

                </tr>
            {% endfor %}

        </table>
        <button class="btn btn-primary form-btn" type="submit" class="btn btn-default">Validate</button>
    </form>
{% endblock %}